version: '3.3'

services:
    db:
        build: ./db/
        image: icinga2-postgres:latest
        restart: always
        environment:
          POSTGRES_USER: postgres
        volumes:
            - postgres:/var/lib/postgresql/data/
        networks:
            - icinga

    core:
        build: ./core/
        depends_on:
          - db
          - timeseries
        image: icinga2-core:latest
        restart: always
        hostname: icinga2
        privileged: true
        volumes:
           - icinga_config:/etc/icinga2/
           - icinga_runtime:/var/lib/icinga2/
        ports:
          - "5665:5665"
        networks:
           - icinga
           - timeseries
    web:
        build: ./web/
        depends_on:
          - core
        image: icinga2-web:latest
        restart: always
        hostname: icingaweb2
        networks:
          - icinga
        ports:
          - "8080:80"
        volumes:
          - web:/etc/icingaweb2
          - apache:/usr/share/icingaweb2/public

    timeseries:
        image: influxdb:latest
        restart: always
        environment:
          INFLUXDB_DB: icinga2
          INFLUXDB_ADMIN_USER: admin
          INFLUXDB_ADMIN_PASSWORD: password
          INFLUXDB_USER: icinga
          INFLUXDB_USER_PASSWORD: icinga
        volumes:
          - influx:/var/lib/influxdb
        ports:
          - "8086:8086"
        networks:
          - timeseries

    visuslisation:
        image: grafana/grafana:latest
        depends_on:
          - timeseries
        restart: always
        hostname: grafana
        networks:
          - timeseries
        ports:
          - "8081:3000"
        volumes:
          - grafana_data:/var/lib/grafana/
          - grafana_config:/etc/grafana/

volumes:
    postgres:
    icinga_config:
    icinga_runtime:
    influx:
    web:
    apache:
    grafana_data:
    grafana_config:

networks:
    icinga:
    timeseries:
